### ISSUE TITLE
Add output support.

### ISSUE THREAD

**Issue by schalkventer** [ShailenNaidoo/Netlify#1]
Never resolves initial status fetch. Adding extension output in VS Code will help resolving issues.

![image](https://user-images.githubusercontent.com/14258328/65408656-15d4e080-dde6-11e9-9285-a479c38e7be1.png)

![image](https://user-images.githubusercontent.com/14258328/65408682-29804700-dde6-11e9-93af-42d6c0e92853.png)

**Comment by ShailenNaidoo** [comment]
I added some context
