### ISSUE TITLE
Unable to use the extension

### ISSUE THREAD

**Issue by FrankySnow** [ShailenNaidoo/Netlify#18]
Hello,
after configuring all the parameters (yes, I've double checked them) in my workspace settings and restarting VS Code, I am unable to use the extension.

The status bar shows "Netlify build status: Failed to fetch deploy status" and when I launch a command, there is an error "command *** not found". The Netlify explorer shows "No deploys summary".

Am I missing something ?

**Comment by ShailenNaidoo** [comment]
Are you able to send a screenshot of your configuration for Netlify?

**Comment by rohiaudio** [comment]
I'm also having this issue. "View latest Netlify deploy" works no problem, but I do not get the deploy summary in the Netlify explorer tab, and "output" section of the terminal displays this:

Failed to fetch deploy status. Stopping polling on Netlify Deploys API.

I also have checked and rechecked the workspace parameters and restarted multiple times. Any thoughts?

**Comment by rohiaudio** [comment]
I've been able to make this extension work by downgrading to version 7.0. Sadly, the deploy panel isn't available, but all I really need is the build status at the bottom anyway. Hopefully future versions address this, as this is an excellent extension for Netlify users!

**Comment by ShailenNaidoo** [comment]
@rohiaudio PRs are welcome! :smiley:

**Comment by FrankySnow** [comment]
@ShailenNaidoo According to the docs, I've set `netlify.site_id`, `netlify.build_hook`, `netlify.api_token` and `netlify.set_interval` in the `.vscode/settings.json` of my Workspace.

> I've been able to make this extension work by downgrading to version 7.0. Sadly, the deploy panel isn't available, but all I really need is the build status at the bottom anyway. Hopefully future versions address this, as this is an excellent extension for Netlify users!

@rohiaudio How and what to downgrade to version 7.0 ? AFAIK this extension is currently at 1.4.0

**Comment by rohiaudio** [comment]
> @ShailenNaidoo According to the docs, I've set `netlify.site_id`, `netlify.build_hook`, `netlify.api_token` and `netlify.set_interval` in the `.vscode/settings.json` of my Workspace.
> 
> > I've been able to make this extension work by downgrading to version 7.0. Sadly, the deploy panel isn't available, but all I really need is the build status at the bottom anyway. Hopefully future versions address this, as this is an excellent extension for Netlify users!
> 
> @rohiaudio How and what to downgrade to version 7.0 ? AFAIK this extension is currently at 1.4.0

Version 0.7, my apologies.

**Comment by mickmcg** [comment]
I have the same "Netlify Build Status: Failed to fetch deploy status" with latest 1.4.0. 0.7 downgrade also worked for me.

**Comment by ShailenNaidoo** [comment]
Okay thanks for the notification, I'll look into it tomorrow

**Comment by ShailenNaidoo** [comment]
@mickmcg Can you send me your output from the "Output" panel, just select "Netlify" in the list

**Comment by ShailenNaidoo** [comment]
@FrankySnow Is the site that you want to observe "private" or "public"?

**Comment by FrankySnow** [comment]
> @FrankySnow Is the site that you want to observe "private" or "public"?

@ShailenNaidoo the site is public but his repo is private

**Comment by ShailenNaidoo** [comment]
It appears that Netlify has removed the deploy summary information from the `deploys` API, I'll need to investigate further but it seems that the Netlify Sidebar will need to be removed if the summary information is not available

**Comment by chriskyfung** [comment]
> It appears that Netlify has removed the deploy summary information from the `deploys` API, I'll need to investigate further but it seems that the Netlify Sidebar will need to be removed if the summary information is not available

@ShailenNaidoo Is that the reason why nothing displays on the sidebar?

**Comment by ShailenNaidoo** [comment]
Yes that is correct, I'll need to remove it in the next release
