### ISSUE TITLE
Netlify explorer: deploy summary is empty

### ISSUE THREAD

**Issue by oezkancodes** [ShailenNaidoo/Netlify#21]
Trigger build hook and fetch status are working perfectly, **except for the deploy summary**. It is just empty with a note "No deploy summary".

I have configured as follows:
``` json
{
  "netlify.api_token": "<api_token>",
  "netlify.build_hook": "https://api.netlify.com/build_hooks/<id>",
  "netlify.site_id": "<site_id>.netlify.com"
}
```

I'm on VSCode March 2021 v1.55. Any ideas?

**Comment by ShailenNaidoo** [comment]
Hi there

The deploy summary will have to be removed as Netlify has deprecated the
API needed for that feature

**Comment by oezkancodes** [comment]
Thank you for the information 👍
